name: Prepare

description: Prepares the repo for a typical CI job

inputs:
  node-version:
    description: 'The Node.js version to use'
    required: true
    default: '24'

runs:
  using: composite

  steps:
    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'
        cache-dependency-path: ./yarn.lock
        check-latest: true

    - name: Install dependencies on ${{ inputs.node-version }}
      run: yarn install
      shell: bash
