name: CI
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  check-lint-and-formatting:
    name: Check lint and formatting
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [20.x]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Check for duplicate packages
        run: yarn dedupe --check --strategy highest

      - name: Check formatting
        run: yarn workspaces foreach -Ap -j unlimited run format-check

      - name: Lint files
        run: yarn workspaces foreach -Ap -j unlimited run lint

      - name: Run type tests
        run: yarn workspaces foreach -Ap -j unlimited run test-types

  build:
    defaults:
      run:
        working-directory: packages/${{ matrix.packages }}

    name: Build ${{ matrix.packages }} on ${{ matrix.os }} with Node.js ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [20.x]
        packages: ['eslint', 'prettier', 'typescript', 'vitest']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run publint
        run: npx publint@latest --strict

      - name: Pack ${{ matrix.packages }}
        id: pack
        run: yarn pack

      - name: Upload artifact ${{ matrix.packages }}
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: ${{ matrix.packages }}
          path: packages/${{ matrix.packages }}/package.tgz

      - name: Did we fail?
        if: failure()
        run: ls -R

  test:
    name: Test ${{ matrix.packages }} on ${{ matrix.os }} with Node.js ${{ matrix.node }}
    needs: [build]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [20.x]
        packages: ['eslint', 'prettier', 'typescript', 'vitest']
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Download build artifact for ${{ matrix.packages }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.packages }}
          path: examples/${{ matrix.packages }}

      - name: Install dependencies
        run: yarn install

      - name: Display folder structure of examples/${{ matrix.packages }}
        run: ls -R examples/${{ matrix.packages }}

      - name: Install build artifact for ${{ matrix.packages }}
        working-directory: examples/${{ matrix.packages }}
        run: yarn add -D ./package.tgz

      - name: Test examples for ${{ matrix.packages }}
        working-directory: examples/${{ matrix.packages }}
        run: yarn test

      - name: Did we fail?
        if: failure()
        run: ls -R

  are-the-types-wrong:
    name: Check if the type definitions are correct
    runs-on: ${{ matrix.os }}
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        node: [20.x]
        packages: ['eslint', 'prettier', 'typescript', 'vitest']
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Download build artifact for ${{ matrix.packages }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.packages }}
          path: packages/${{ matrix.packages }}

      - name: Display folder structure
        run: ls -l .

      - name: Run are-the-types-wrong
        run: npx @arethetypeswrong/cli@latest packages/${{ matrix.packages }}/package.tgz --format table

      - name: Did we fail?
        if: failure()
        run: ls -R
