name: CI
on: [push, pull_request]

jobs:
  build:
    defaults:
      run:
        working-directory: packages/${{ matrix.packages }}

    name: Build ${{ matrix.packages }} on ${{ matrix.os }} with Node.js ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [20.x]
        packages: ['eslint', 'prettier', 'typescript', 'vitest']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run publint
        run: npx publint@latest --strict

      - name: Pack ${{ matrix.packages }}
        id: pack
        run: yarn pack

      - name: Upload artifact ${{ matrix.packages }}
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: ${{ matrix.packages }}-artifact
          path: packages/${{ matrix.packages }}/*.tgz

      - name: Did we fail?
        if: failure()
        run: ls -R

  test:
    name: Test ${{ matrix.packages }} on ${{ matrix.os }} with Node.js ${{ matrix.node }}
    needs: [build]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [18.x, 20.x]
        packages: ['eslint', 'prettier', 'typescript', 'vitest']
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.packages }}-artifact
          path: examples/${{ matrix.packages }}

      - name: Display structure of downloaded artifact
        run: ls -R examples/${{ matrix.packages }}

      - name: Install dependencies
        working-directory: examples/${{ matrix.packages }}
        run: yarn install

      - name: Install build artifact for ${{ matrix.packages }}
        working-directory: examples/${{ matrix.packages }}
        run: yarn add ./package.tgz

      - name: Test examples for ${{ matrix.packages }}
        working-directory: examples/${{ matrix.packages }}
        run: yarn test

      - name: Did we fail?
        if: failure()
        run: ls -R

  are-the-types-wrong:
    name: Check if the type definitions are correct
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [20.x]
        packages: ['eslint', 'prettier', 'typescript', 'vitest']
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.packages }}-artifact
          path: packages/${{ matrix.packages }}

      - name: show folder
        run: ls -l .

      - name: Run are-the-types-wrong
        run: npx @arethetypeswrong/cli@latest ./package.tgz --format table

      - name: Did we fail?
        if: failure()
        run: ls -R
